-- CREATE SEQUENCE probook.AUTONUMBER_SEQ;

-- 発番用トリガー
CREATE OR REPLACE TRIGGER probook.AUTONUMBER_NUMBERING
BEFORE INSERT ON users
FOR EACH ROW
DECLARE
    eIKENAIYO        EXCEPTION;
    -- (オプション) 例外の付け替え DUP_VAL_ON_INDEX
    PRAGMA EXCEPTION_INIT(eIKENAIYO, -1); 
BEGIN
    IF (:NEW.user_id IS NOT NULL) THEN
        RAISE eIKENAIYO;
    END IF;
    -- Oracle 11g 以降
    :NEW.user_id := USERID_SEQ.NEXTVAL ;
    -- Oracle 11g より前
    -- SELECT AUTONUMBER_SEQ.NEXTVAL INTO :NEW.SEQ_NO FROM DUAL ;
END;
